# Generated by Django 6.0.7 on 2026-07-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakerySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=500.0, max_digits=6)),
            ],
        ),
    ]
