# Generated by Django 6.0.7 on 2026-07-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_bakerysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('percentage', 'Discount Percentage'), ('bogo', 'Buy One Get One (BOGO)'), ('festival', 'Festival Offer (% Discount)')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
