# Generated by Django 6.0.7 on 2026-07-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('payment_received', 'Advance Payment Received'), ('accepted', 'Order Accepted'), ('preparing', 'Preparing'), ('ready', 'Order is Ready'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=20),
        ),
    ]
