# Generated by Django 6.0.7 on 2026-07-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
